<h3>Giveaway Rules</h3>
<p>By submitting an entry to the Sweepstakes (the “Sweepstakes”), you acknowledge that you have read and agree to be bound by these Official Rules and the decisions of [site_name], and that you satisfy all eligibility requirements.</p>
<p>The Sweepstakes (“Sweepstakes”) is open to all humans age 21 or older at time of entry. Residents of Taiwan, South Korea, Portugal, Italy, Austria, China, Russia, Hong Kong, Greece, France, Japan, Spain, and Czech Republic are not eligible to enter or win. Employees of [site_name] (the “Sponsor”), its respective parent, subsidiaries, affiliates, advertising and promotion agencies, distributors, merchants involved with this Sweepstakes, and their immediate family members and/or those living in the same household of each are not eligible to enter or win. Sweepstakes governed by [address_country] law. Sweepstakes is subject to all applicable federal, state and local laws and regulations. Void where prohibited by law. No purchase necessary to enter or win. A purchase will not improve your chances of winning.</p>
<h4>HOW TO ENTER:</h4>
<p>To enter the Sweepstakes, follow all onscreen instructions to complete and submit the online entry form (“Primary Entry”). You can earn an Additional Entry in the Sweepstakes when you send the Sweepstakes page to a friend, age 21 or older, by following the Additional Entry instructions on the screen (“Additional Entry”). The friend must enter the sweepstakes through your referral in order to get an additional entry. All entries must be received by [date_end] (“Sweepstakes Entry Period”). Online entrants subject to all notices posted online including but not limited to Sponsor’s privacy policy.</p>
<h4>PRIZES &amp; APPROXIMATE RETAIL VALUES (“ARV”):</h4>
<p>Maximum ARV of all prizes: [prize_value]. Prize includes: [prize_name]. If winner is unable to receive payment then prize will be forfeited, and an alternate winner may be selected in accordance with these Official Rules from among the remaining eligible entries for that prize. Prizes may not be transferred or assigned except by Sponsor.</p>
<h4>ODDS:</h4>
<p>Odds of winning depend on number of eligible entries received during the Sweepstakes Entry Period.</p>
<h4>THE FOLLOWING APPLIES TO THE ABOVE:</h4>
<p>Winners will be selected in a random drawing from all eligible entries received. Random drawing will be conducted on or about [date_awarded] by a representative from the Sponsor whose decisions are final. Winners will be notified by email and/or mail and at the judges’ discretion, will be required to complete and return an email confirmation of prize acceptance and possibly a Affidavit of Eligibility and Liability and a Publicity Release (“Affidavit/Release”) within 7 days of notification, or an alternate winner will be selected. Prize awarded within 30 days after receipt and verification of completed Affidavit/Release or prize notification. If a potential winner cannot be contacted, or if Affidavit/Release is returned as undeliverable or if the selected winner cannot accept or receive the prize for any reason, or he/she is not in compliance with these Official Rules, the prize will be forfeited and may be awarded to an alternate winner. If a winner is otherwise eligible under these Official Rules, but is nevertheless deemed a minor in his or her state of primary residence, the prize will be awarded in the name of winner’s parent or legal guardian who will be required to execute affidavit on minor’s behalf. No substitutions are permitted except if prize is unavailable, in which case a prize of equal or greater value will be awarded. Prize is not redeemable for cash and non-assignable and non-transferable except to a surviving spouse. Winner is responsible for all federal, state, local sales and income taxes. Any other incidental expenses on prize not specified herein are the sole responsibility of winner. Entry and acceptance of prize constitute permission to use winner’s name, prize won, hometown and likeness for online posting and promotional purposes without further compensation, except where prohibited by law. Limit: one prize per household. Prize is guaranteed to be awarded. If [site_name] goes bankrupt or out of business then the year they go out of business is the last year of payment for the premium service. If [site_name] is acquired or merges, it’s the new owners discretion to keep paying for the premium service. If we go bankrupt or out of business then the last year they are in business will be the payment for the premium service. Cash value of the prize cannot be redeemed.</p>
<p>Participating entrants agree to these Official Rules and the decisions of the Sponsor, and release, defend and hold harmless the Sponsor and its affiliated companies, and all other businesses involved in this Sweepstakes, as well as the employees, officers, directors and agents of each, from all claims and liability relating to their participation, acceptance and use or misuse of prize. Winner assumes all liability for any injury or damage caused or claimed to be caused, by participation in this Sweepstakes or use or redemption of prize. Sponsor is not responsible for any typographical or other error in the printing of the offer, administration of the Sweepstakes or in the announcement of the prize.</p>
<p>Winner acknowledges the Sponsor and all other businesses concerned with this Sweepstakes and their agents do not make, nor are in any manner responsible for any warranty, representations, expressed or implied, in fact or in law, relative the quality, conditions, fitness or merchantability of any aspect of prize.</p>
<p>In the event of a dispute over the identity of an online entrant, entry will be deemed submitted by the “Authorized Account Holder” of the e-mail address submitted at time of entry. Authorized Account Holder means the natural person who is assigned to an e-mail address by an Internet access provider, online service provider, or other organization that is responsible for assigning e-mail addresses for the domain associated with the submitted e-mail address. Entry materials/data that have been tampered with or altered, or mass entries or entries generated by a script, macro or use of automated devices are void. The Sponsor is not responsible for: (i) lost, late, misdirected, damaged, illegible or incomplete entries; or (ii) error, omission, interruption, deletion, defect, delay in operations or transmission, theft or destruction or unauthorized access to or alterations of entry materials, or for technical, network, telephone equipment, electronic, computer, hardware or software malfunctions of any kind, or inaccurate transmission of or failure to receive entry information by Sponsor on account of technical problems or traffic congestion on the Internet or at any web site or any combination thereof; or (iii) any injury or damage to entrant’s or any other person’s computer related to or resulting from participating in the Sweepstakes. By participating in the Sweepstakes, you (i) agree to be bound by these Official Rules, including all eligibility requirements, and (ii) agree to be bound by the decisions of Sponsor and the independent judging organization, which are final and binding in all matters relating to the Sweepstakes. Failure to comply with these Official Rules may result in disqualification from the Sweepstakes. Sponsor reserves the right to permanently disqualify from any sweepstakes it sponsors any person it believes has intentionally violated these Official Rules and cancel the Sweepstakes if it becomes technically corrupted (including if a computer virus, bot or system malfunction inalterably impairs its ability to conduct the Sweepstakes), and to select winner from among all eligible entries received prior to withdrawal. Legal Warning: ANY ATTEMPT BY AN individual, whether or not an ENTRANT, TO DELIBERATELY DAMAGE, destroy, tamper or vandalize this WEB SITE OR interfere with the OPERATION OF THE SWEEPSTAKES, IS A VIOLATION OF CRIMINAL AND CIVIL LAWS and SPONSOR RESERVES THE RIGHT TO SEEK DAMAGES and diligently pursue all remedies against ANY SUCH individual TO THE FULLEST EXTENT PERMITTED BY LAW.</p>
<h4>ARBITRATION:</h4>
<p>This Sweepstakes shall be governed by and interpreted under the laws of the State of [address_state], [address_country]. without regard to its conflicts of laws provisions. By participating, entrants agree that any and all disputes arising out of or relating in any way to this Sweepstakes shall be litigated only in courts sitting in [address_city], [address_state], [address_country].</p>
<h4>WINNERS LIST:</h4>
<p>For a winners list (available after [date_awarded]), send a stamped, self-addressed envelope by [date_awarded] to:</p>
<p>
Sweepstakes Winner<br />
[site_name]<br />
[address_street]<br />
[address_city]<br />
[address_state], [address_country], [address_zip]
</p>
<h4>CONFIDENTIALITY:</h4>
<p>By entering, the information you are only signing up for the [site_name] newsletter. Your information will never be sold to anyone. You can unsubscribe easily from [site_name] by clicking on the unsubscribe link in the bottom right of our daily emails. Information provided by you to participate in this Sweepstakes is subject to Sponsor’s privacy policy located at [site_url]/privacy/</p>
<h4>SPONSOR:</h4>
<p>
[site_name]<br />
[address_street]<br />
[address_city]<br />
[address_state], [address_country], [address_zip]
</p>
<p>The personal information collected from each entrant in the course of the Sweepstakes will be used by [site_name] for the purposes of administration of the Sweepstakes and as otherwise permitted in accordance with [site_name]’s Privacy Policy. Please see [site_name]’s Terms of Service for more information. [site_name] reserves the right to alter any rules of any sweepstakes at anytime. If you have any questions or complaints about a [site_name] sweepstakes, please contact [contact_email].</p>
[#prize_brand]<p>Sweepstakes is not sponsored, endorsed or administered by [prize_brand], nor is [prize_brand] associated with the Sweepstakes in any way. You understand that you are providing information to the Sponsor and not to [prize_brand]. Any questions, comments or complaints regarding the Sweepstakes must be directed to the Sponsor or Administrator, and not to [prize_brand]. [prize_brand] is a registered trademark of [prize_brand].</p>[/prize_brand]
